if [ -d ~/configs/bash.d ]; then
    for i in ~/configs/bash.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    done
    unset i
fi

export PATH=~/bin:/usr/local/bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# activate rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# added by Anaconda3 4.4.0 installer
export PATH="/Users/23056791/anaconda/bin:$PATH"

# direnv
eval "$(direnv hook bash)"

# bash_autocompletion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

