if [ -d ~/configs/bash.d ]; then
    for i in ~/configs/bash.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    done
    unset i
fi

export PATH=~/bin:$PATH

# MacPorts Installer addition on 2011-08-07_at_16:28:18:
#  adding an appropriate PATH variable for use with MacPorts.
export PATH=/usr/local/sbin:/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
