if [ -d ~/configs/bash.d ]; then
    for i in ~/configs/bash.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    done
    unset i
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# added by travis gem
[ -f /Users/23056791/.travis/travis.sh ] && source /Users/23056791/.travis/travis.sh
