if [ "" != "$BASH" ]; then
	__git_ps1 () 
	{ 
	    local b="$(git symbolic-ref HEAD 2>/dev/null)";
	    if [ -n "$b" ]; then
	        printf ",%s" "${b##refs/heads/}";
	    fi
	}
	export PS1='[\@] \[\e[0;32m\]\u\[\e[0;0m@\e[0;33m\]\h\[\e[0;0m\]\n\!,\[\e[1;33m\]$?\[\e[1;35m\]$(__git_ps1 "(%s)") \[\e[1;32m\]\w\[\e[0;0m\] \$ '
fi
